// English labels for the survey form (from vt-household-survey reference UI)
export const surveyLabels = {
  'nav.newSurvey': 'New survey',
  'common.loading': 'Loading…',
  'common.back': 'Back',
  'common.continue': 'Continue',
  'common.select': 'Select',
  'common.optional': 'Optional',
  'survey.section.identity': 'QR ID, contact & address',
  'survey.section.household': 'Household information',
  'survey.section.location': 'Geographic GPS location',
  'survey.section.photo': 'Household photograph',
  'survey.section.issues': 'Major issues & grievances',
  'survey.section.schemes': 'Government schemes availed',
  'survey.qrId': 'QR ID (manual entry from QR plate)',
  'survey.qrIdPlaceholder': '6-digit QR ID',
  'survey.check': 'Check',
  'survey.checking': 'Checking…',
  'survey.codeAvailable': 'This QR ID is available.',
  'survey.codeTaken': 'This QR ID is already registered. Use a different one.',
  'survey.name': 'Name',
  'survey.namePlaceholder': 'Full name',
  'survey.mobile': 'Mobile No.',
  'survey.mobilePlaceholder': '10-digit mobile number',
  'survey.email': 'Email',
  'survey.state': 'State',
  'survey.wardPanchayat': 'Ward/Panchayat',
  'survey.wardPanchayatPlaceholder': 'Ward no. or Gram Panchayat name',
  'survey.propertyType': 'Property Type',
  'survey.locationHint': 'Stand at the household entrance and capture its GPS coordinates.',
  'survey.getLocation': 'Get Location',
  'survey.gettingLocation': 'Getting location…',
  'survey.locationError': 'Could not get location. Check that location access is allowed for this browser.',
  'survey.latitude': 'Latitude',
  'survey.longitude': 'Longitude',
  'survey.photoHint': 'Capture a live photo of the household, or drag one in.',
  'survey.capturePhoto': 'Capture photo',
  'survey.removePhoto': 'Remove',
  'survey.dragPhoto': 'Drag a photo here, or use the buttons below',
  'survey.district': 'District',
  'survey.taluka': 'Taluka Name',
  'survey.village': 'Village Name',
  'survey.houseNumber': 'House Number',
  'survey.headName': 'Household Head Name',
  'survey.sameAsName': 'Same as the Name entered above.',
  'survey.headMobile': 'Head Mobile Number',
  'survey.sameAsMobile': 'Same as Mobile No. entered above.',
  'survey.headAge': 'Age of Household Head',
  'survey.agePlaceholder': 'Age in years',
  'survey.alternateMobile': 'Alternate Mobile Number',
  'survey.familyMembers': 'House family members number',
  'survey.monthlyIncome': 'Monthly Income Bracket',
  'survey.facilities': 'Available Facilities',
  'survey.occupation': 'Occupation',
  'survey.majorIssues': 'Major issues faced',
  'survey.grievanceDetail': 'Grievances or Problems in Detail',
  'survey.grievancePlaceholder': 'Describe the grievance or problem in detail',
  'survey.govtSchemes': 'Government Facility/Schemes Availed',
  'survey.errRequired': 'This field is required',
  'survey.errInvalidPhone': 'Enter a valid 10-digit phone number',
  'survey.errInvalidEmail': 'Enter a valid email address',
  'survey.errInvalidAge': 'Enter a valid age between 18 and 120',
  'survey.submit': 'Submit survey',
  'survey.submitting': 'Submitting…',
  'survey.saveChanges': 'Save changes',
  'survey.saving': 'Saving…',
  'survey.recorded': 'Household recorded',
  'survey.recordedHint': 'Print and paste the QR plate assigned to this house.',
  'survey.citizenPasswordLabel': 'Citizen login password',
  'survey.citizenPasswordNote': "Give this 8-digit password to the household along with their QR ID. It's needed to log in to the citizen portal and will not be shown again.",
  'survey.startAnother': 'Start another survey',
  'survey.viewMySurveys': 'View my surveys',
  'survey.updated': 'Survey updated',
  'survey.updatedHint': 'Changes to household record have been saved.',
  'survey.backToMySurveys': 'Back to my surveys',
  'survey.viewSurvey': 'View my surveys',
  'nav.mySurveys': 'Edit survey'
}

export function t(key) {
  return surveyLabels[key] || key
}
